"""Reusable FFmpeg-backed video editing helpers."""

from .media import (
    MediaFile,
    clip,
    convert_audio,
    convert_to_mp3,
    extract_audio_file,
    extract_frames,
    fetch_info,
    generate_thumbnails,
    generate_thumbnails_at,
    legacy_concat_videos,
    list_videos,
    normalize_video,
    normalize_videos,
    probe,
    pull_video,
)
from .models import (
    AudioMix,
    AudioTrack,
    CanvasManifest,
    CanvasPanel,
    CutDefinition,
    OutputDefinition,
    PlaylistItem,
    PlaylistManifest,
    RenderPreset,
    SourceAsset,
    TimelineManifest,
    TimelineSection,
    TitleStyle,
    VolumeRamp,
)
from .operations import (
    assemble_from_manifest,
    concat_playlist,
    concat_videos,
    extract_audio,
    load_manifest,
    plan_render,
    probe_media,
    render_canvas,
    render_playlist,
    render_timeline,
    summarize_plan,
    trim_video,
)
from .service import FFmpegTools, VideoEditingService

__all__ = [
    "AudioMix",
    "AudioTrack",
    "CanvasManifest",
    "CanvasPanel",
    "CutDefinition",
    "FFmpegTools",
    "MediaFile",
    "OutputDefinition",
    "PlaylistItem",
    "PlaylistManifest",
    "RenderPreset",
    "SourceAsset",
    "TimelineManifest",
    "TimelineSection",
    "TitleStyle",
    "VideoEditingService",
    "VolumeRamp",
    "assemble_from_manifest",
    "clip",
    "concat_playlist",
    "concat_videos",
    "convert_audio",
    "convert_to_mp3",
    "extract_audio",
    "extract_audio_file",
    "extract_frames",
    "fetch_info",
    "generate_thumbnails",
    "generate_thumbnails_at",
    "legacy_concat_videos",
    "list_videos",
    "load_manifest",
    "normalize_video",
    "normalize_videos",
    "plan_render",
    "probe",
    "probe_media",
    "pull_video",
    "render_canvas",
    "render_playlist",
    "render_timeline",
    "summarize_plan",
    "trim_video",
]

__version__ = "0.1.0"
